# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    # trigger the appropriate release type when merging bumps:
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-minor', 'version-update:semver-patch']
