name: 'master'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      needs-update: ${{ steps.diff.outcome != 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - run: npm run all
      - name: Check for changes (fail if we forgot to update lib output)
        run: git diff --quiet lib
        id: diff
        continue-on-error: true

      - name: Set up commit signing w/ GPG
        if: ${{ steps.diff.outcome != 'success' }}
        id: configure
        uses: tradeshift/actions-git/configure-from-gpg-key@v1
        with:
          gpg-key: ${{ secrets.TRADESHIFTCI_GPG_KEY }}

      - name: PR build changes if needed
        uses: tradeshift/create-pull-request@v3
        if: ${{ steps.diff.outcome != 'success' }}
        with:
          commit-message: "build: update dist folder"
          branch: release-update-dist
          title: "Update for release: update package runtime"
          body: |
            This PR is created automatically because the repo has been changed
            without updating the packaged version in the `dist` folder.
            Before these changes can be released, the `dist` folder has to be
            updated. By merging this when the build is green, a new release
            will be created based on the list of changes since the last release.
            For more info see [semantic-release.gitbook.io/semantic-release/](https://semantic-release.gitbook.io/semantic-release/)
          token: ${{ secrets.GH_TOKEN }}
          committer: ${{ steps.configure.outputs.user }}
          author: ${{ steps.configure.outputs.user }}

  self-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory
        with:
          copyWithoutRender: |
            .static
          targetPath: ./output
          values: |
            {
              "name": "App",
              "type": "public"
            }
      - uses: actions/setup-node@v2
        with:
            node-version: 16
      # run assertion script
      - run: node output/index.js
  release:
    runs-on: ubuntu-20.04
    needs: [self-test, build]
    steps:
      - uses: actions/checkout@v2
      - uses: tradeshift/actions-semantic-release@v1
        id: semantic-release
        with:
          branches: |
            [
              'master'
            ]
          check_name: Semantic release
          registry: https://npm.pkg.github.com/
          npm_publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Action tags (major version tag)
        if: ${{ steps.semantic-release.outputs.new_release_published }}
        run: |
          git tag -f v${{ steps.semantic-release.outputs.new_release_major_version }}
          git push -f origin v${{ steps.semantic-release.outputs.new_release_major_version }}
